[package]
name = "stockdata"
version = "0.1.0"
authors = ["Gustavo Noronha Silva <gustavo.noronha@collabora.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
yahoo-finance = "0.2"