[package]
name = "multi-output"
version = "0.1.0"
authors = ["Gustavo Noronha Silva <gustavo@noronha.eti.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bus = "2.2.3"
dashmap = "3.11.10"
crossbeam = "0.7.3"
